trigger: time_amount
time_amount: 300
backups_dir: /Users/Mik3/sarcophagus/backups
backup_hidden_files: false
files:
- /Users/Mik3/sarcophagus/Flygon
- /Users/Mik3/sarcophagus/test
- /Users/Mik3/sarcophagus/brubru.txt